version: '2'
services:
    hf-mariadb:
        image: mariadb:10.3.7
        # volumes:
        #     - ~/volumes/jhipster/hfuaa/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=goot
            - MYSQL_DATABASE=hfuaa
            - MYSQL_ROOT_PASSWORD=mysql  
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
